[application]
name = "netcalc-rs"
default_icon = "assets/icon.png"

[bundle]
identifier = "com.netcalcrs.app"
publisher = "Betzalel75"
icon = ["assets/icon.png"]

formats = ["deb", "rpm"]

[web.app]

# HTML title tag content
title = "netcalc-rs"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/"]

# Additional JavaScript files
script = ["assets/js/index.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
